### ISSUE TITLE
When will be developer report 2021

### ISSUE THREAD

**Issue by yangwao** [electric-capital/developer-reports#1]
Hello @mariashen I've checked that you will be printing new report, is there any pre-data to take peak on? 

We've recently sorted stuff https://github.com/electric-capital/crypto-ecosystems/issues/166 so we won't skew numbers much! :)
https://github.com/kodadot/nft-gallery/issues/1278

**Comment by LeadManPL** [comment]
Looks like it is already [here](https://github.com/electric-capital/developer-reports/blob/master/dev_report_2021_updated_012622.pdf)

Please close this issue
